version: '3.4'

services: 
    # Simple setup
    # nginx:
    #     image: nginx
    #     volumes: 
    #         - ./nginx.conf:/etc/nginx/nginx.conf
    #     ports: 
    #         - 8080:8081

    # Setup via Dockerfile
    nginx:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - 8080:8081
    